version: '3'
services:
  vue-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: npm run dev

  vue-app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
